FROM openjdk
MAINTAINER Mostafa Salem <mostafasalem95@gmail.com>
ADD target/vehicles-gateway-service-0.0.1.jar vehicles-gateway-service-0.0.1.jar
ENTRYPOINT ["java", "-jar", "/vehicles-gateway-service-0.0.1.jar"]
EXPOSE 8765