FROM openjdk
MAINTAINER Mostafa Salem <mostafasalem95@gmail.com>
ADD target/vehicles-discovery-server-0.0.1.jar vehicles-discovery-server-0.0.1.jar
ENTRYPOINT ["java", "-jar", "/vehicles-discovery-server-0.0.1.jar"]
EXPOSE 8761