FROM openjdk
MAINTAINER Mostafa Salem <mostafasalem95@gmail.com>
ADD target/vehicles-status-service-0.0.1.jar vehicles-status-service-0.0.1.jar
ENTRYPOINT ["java", "-jar", "/vehicles-status-service-0.0.1.jar"]
EXPOSE 8100